#+title: Example Configurations

* Example Configurations

Rational Emacs supports user customization through a =config.el= file
in one of the following directories.

- =~/.rational-emacs/=
- =~/.config/rational-emacs/=

You can either edit =config.el= directly or tangle it from =config.org= via
[[https://orgmode.org/worg/org-contrib/babel/intro.html][Org-Babel]]. You'll find an example of both variants in this directory:

- =example-config.el=
- =example-config.org=

Pick either one to get you started. Copy it to one of the above-mentioned
directories as =config.el= or =config.org=, respectively.

* Back in Time – Using =straight.el=

Early in the lifetime of this project, the project used =straight.el=
to install packages. However, after a [[https://github.com/SystemCrafters/rational-emacs/issues/94][discussion]], the community
decided to move to using =package.el= instead as it lined up with the
principles of the project more than =straight.el=; notably, it is
built in and one of the principles specifically states "Prioritize
built-in Emacs functionality".

However, as many people who started with this project preferred to use
=straight.el=, the move to =package.el= was suboptimal.

If you prefer to use =straight.el= instead of =package.el= under the hood, put the
following two snippets into your configuration files:

** early-config.el
Disable =package.el= during startup:
#+begin_src emacs-lisp :tangle ./early-config.el
  (setq package-enable-at-startup nil)
#+end_src

** config.el
Overwrite the function =rational-package-install-package= using straight.el
instead of package.el:
#+begin_src emacs-lisp :tangle ./config.el
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (defmacro rational-package-install-package (package)
    "Install PACKAGE using straight"
    `(straight-use-package ,package))
#+end_src

-----
# Local Variables:
# fill-column: 80
# eval: (auto-fill-mode 1)
# End:
