#+title: Example Configurations

* Example Configurations

Crafted Emacs supports user customization through a =config.el= file
in one of the following directories.

- =~/.crafted-emacs/=
- =~/.config/crafted-emacs/=

You can either edit =config.el= directly or tangle it from =config.org= via
[[https://orgmode.org/worg/org-contrib/babel/intro.html][Org-Babel]]. You'll find an example of both variants in this directory:

- =example-config.el=
- =example-config.org=

Pick either one to get you started. Copy it to one of the above-mentioned
directories as =config.el= or =config.org=, respectively.

* Back in Time – Using =straight.el=

Early in the lifetime of this project, the project used =straight.el=
to install packages. However, after a [[https://github.com/SystemCrafters/crafted-emacs/issues/94][discussion]], the community
decided to move to using =package.el= instead as it lined up with the
principles of the project more than =straight.el=; notably, it is
built in and one of the principles specifically states "Prioritize
built-in Emacs functionality".

However, as many people who started with this project preferred to use
=straight.el=, the move to =package.el= was suboptimal.

If you prefer to use =straight.el= instead of =package.el= under the hood, put the
following snippet into your early configuration file:

** early-config.el
Disable =package.el= during startup:
#+begin_src emacs-lisp :tangle ./early-config.el
  (setq package-enable-at-startup nil)
  (setq crafted-package-system 'straight)
  (crafted-package-bootstrap crafted-package-system)
#+end_src

-----
# Local Variables:
# fill-column: 80
# eval: (auto-fill-mode 1)
# End:
