* Crafted Emacs UI Module

** Installation

To use this module, simply require them in your =init.el= at the appropriate
points.

#+begin_src emacs-lisp
;; add crafted-ui package definitions to selected packages list
(require 'crafted-ui-packages)

;; install the packages
(package-install-selected-packages :noconfirm)

;; Load crafted-ui configuration
(require 'crafted-ui-config)
#+end_src

** Description
The ~crafted-ui~ module provides a few interface customizations.

It installs the packages

- all-the-icons :: Various icon fonts to be used by Emacs and packages
- helpful :: An augmentation for the built-in Emacs help that provides more
             context.
- elisp-demos :: Code examples that can be displayed by helpful.

It further provides custom variables which can be used to turn on line
numbers in certain major modes (i.e. ~prog-mode~ and ~conf-mode~) while leaving
them turned off for others.   

*** Icons with ~all-the-icons~

 For ~all-the-icons~ to work, the necessary fonts need to be installed on
your system. If you see a "stop"-icon with an exclamation mark at the
beginning of this paragraph, you're good to go.

If not, you can run =M-x all-the-icons-install-fonts= to download the
necessary fonts. On most OSes, they get installed automatically by that
command. On Windows however, they are only downloaded and must be
installed manually.

*** Line numbers

If you want to turn on line numbers for some major modes but leave them
off for others, set ~crafted-ui-display-line-numbers~ to non-nil in your
init.el.

#+begin_src emacs-lisp 
  (customize-set-variable 'crafted-ui-display-line-numbers t)
#+end_src

By default, this turns *on* line numbers for:
- prog-mode, i.e. all programming major modes (Elisp, Python, C etc.)
- conf-mode, i.e. Unix and Windows Conf files and Java properties

By default, it explicitly turns *off* line numbers for:
- org-mode
  
You can change the default behaviour by customizing the variables
~crafted-ui-line-numbers-enabled-modes~ and
~crafted-ui-line-numbers-disabled-modes~ respectively.

For example:
#+begin_src emacs-lisp
  ;; turn off line numbers for python-mode, replacing org-mode
  (customize-set-variable 'crafted-ui-line-numbers-disabled-modes
                          '(python-mode))

  ;; turn on line numbers for markdown-mode, too
  (add-to-list 'crafted-ui-line-numbers-enabled-modes 'markdown mode)

  ;; which is the same as
  (customize-set-variable 'crafted-ui-line-numbers-enabled-modes
                          '(conf-mode prog-mode markdown-mode))
#+end_src
