* Rational Emacs Evil Module

** Installation

To use this module, simply require it in your config.

#+begin_src emacs-lisp
(require 'rational-evil)
#+end_src

** Description

This module installs and sets up four packages to emulate [[https://www.vim.org/][Vim's]] modal editing model.

+ [[https://github.com/emacs-evil/evil][Evil]]: Adds Vim-like modal editing, visual selection, and text objects to Emacs
+ [[https://github.com/emacs-evil/evil-collection][Evil-collection]]:  Vim-like bindings for modes not covered by default in Evil
+ [[https://elpa.gnu.org/packages/undo-tree.html#:~:text=The%20%60undo%2Dtree%2Dmode,of%20never%20losing%20any%20history][Undo-tree]]: Visualizes changes made in your file as a tree
+ [[https://github.com/redguardtoo/evil-nerd-commenter][Evil-nerd-commenter]]: Allows easy commenting of code for many different file types.

More information can be found about each of these packages on their respective pages linked above.

** Customization Variables

This module provides two customizable variables

+ =rational-evil-discourage-arrow-keys=
+ =rational-evil-vim-muscle-memory=.

When =rational-evil-discourage-arrow-keys= is true, arrow keys are disabled in normal and visual mode. When you attempt to use the arrow keys a message will pop up reminding you to use the =HJKL= keys instead.

When =rational-evil-vim-muscle-memory= is true, the variables =evil-want-C-i-jump=, =evil-want-Y-yank-to-eol=, and =evil-want-fine-undo= are all set to true. By default, they are nil. =evil-want-C-i-jump= 



