* Rational Emacs Windows Module

** Installation

To use this module, simply require it in your config.

#+begin_src emacs-lisp
(require 'rational-evil)
#+end_src

** Description

This module enables [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Convenience.html][winner-mode]] and provides a set of keybindings that help you navigate through multiple windows.

=winner-mode= is a minor mode that, when activated, allows you to revert to a prior windows arrangement. It provides two functions to allow this: =winner-undo= and =winner-redo=. These take you to earlier and later windows arrangements respectively. 

To store the keybindings associated with this module, a new keymap is created: =rational-windows-key-map=, Additionally, this module defines a custom variable, =rational-windows-prefix-key=, which allows you to set the prefix key to the keymap. By default, this is set to =C-c w=, but you are free to change it.

Using the default prefix-key, the keybindings defined in this module are

| Key Chord | Function       | Description                            |
|-----------+----------------+----------------------------------------|
| C-c w u   | winner-undo    | Reverts to the previous windows layout |
| C-c w n   | windmove-down  | Moves point to window below            |
| C-c w p   | windmove-up    | Moves point to window above            |
| C-c w b   | windmove-left  | Moves point to window to the left      |
| C-c w f   | windmove-right | Moves point to window to the right     |
